[package]
name = "hitman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "*"
httparse = "1.8"
serde_json = "1.0"
jsonpath = "0.1"
toml = "0.8"
walkdir = "2"
minreq = { version = "2", features = ["https", "json-using-serde"] }
eyre = "0.6.9"
clap = { version = "4.4", features = ["derive"] }
log = { version = "0.4.20", features = ["std"] }
termcolor = "1.4.0"
inquire = { version = "0.6.2", features = ["date"] }
chrono = "0.4.31"
