[package]
name = "http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
httparse = "1.8"
serde_json = "1.0"
toml = "0.8"
minreq = { version = "2", features = ["https", "json-using-serde"] }
